name: 'Build and deploy ASP.Net Core app to Azure Web App: manila-airways-app'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build and Restore
        run: dotnet build AirlineBackend/AirlineBackend.csproj --configuration Release

      - name: Publish
        run: dotnet publish AirlineBackend/AirlineBackend.csproj -c Release -o ${{ github.workspace }}/publish


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'manila-airways-app'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_f9a1f1c725844b218955245257cb969e }}
          package: ${{ github.workspace }}/publish
